### ISSUE TITLE
chefignore missing

### ISSUE THREAD

**Issue by mvangoor** [dnsimple/chef-pdns#118]
Hello,

Our chef infra system has pre-checks in place to enforce certain ignore files are present to stop uploading of files that do not belong to the core cookbook's working (and to limit the bloat of the chef infra server database a bit).

One of these is the 'test' directory.
In the v8.0.2 on supermarket.chef.io release this directory is present and we cannot upload this version because of this.

Could you maybe implement a chefignore like the one sous-chef is using?
Example: https://github.com/sous-chefs/ntp/blob/master/chefignore

I would really appreciate a quick v8.0.3 release with the chefignore in there to remove the test directory.

Thanks!

**Comment by onlyhavecans** [comment]
Hello! Thanks for this! I will try to get this addressed today or Monday. Seems the recent change to delivery is also breaking tests

**Comment by onlyhavecans** [comment]
@mvangoor It seems a lot of our support files were out of date so we couldn't even get tests to pass. I [updated all of them using sous-chef's template repo](https://github.com/dnsimple/chef-pdns/commit/20688a69b9ddbef1e7b640f8e1a94073eee52035) and pushed 8.0.3. Can you please verify your issue is resolved?

**Comment by mvangoor** [comment]
Hello @onlyhavecans,

I can confirm it works as the 8.0.3 cookbook was uploaded to our chef org.

Thanks!

Mike
